CREATE TABLE Users (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Email NVARCHAR(255) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(255) NOT NULL,
  FullName NVARCHAR(255) NOT NULL,
  Role NVARCHAR(50) NOT NULL,
  Department NVARCHAR(255) NULL,
  PhoneNumber NVARCHAR(50) NULL,
  IsActive BIT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  LastLogin DATETIME2 NULL
);

CREATE TABLE Trainees (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  UserId INT NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
  EmployeeId NVARCHAR(50) NOT NULL,
  StartDate DATE NOT NULL,
  EndDate DATE NOT NULL,
  TrainingType NVARCHAR(100) NULL,
  Status NVARCHAR(50) NOT NULL DEFAULT 'active',
  AdvisorId INT NULL REFERENCES Users(Id),
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Tasks (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Title NVARCHAR(255) NOT NULL,
  Description NVARCHAR(MAX) NULL,
  TraineeId INT NOT NULL REFERENCES Trainees(Id) ON DELETE CASCADE,
  DueDate DATE NOT NULL,
  Status NVARCHAR(50) NOT NULL DEFAULT 'pending',
  Priority NVARCHAR(50) NOT NULL DEFAULT 'medium',
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  Progress INT NOT NULL DEFAULT 0,
  LastProgressNote NVARCHAR(MAX) NULL
);

CREATE TABLE ChatSessions (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  SessionType NVARCHAR(20) NOT NULL,
  TraineeId INT NULL REFERENCES Trainees(Id) ON DELETE CASCADE,
  AdvisorId INT NULL REFERENCES Users(Id),
  Participant1Id INT NULL REFERENCES Users(Id),
  Participant2Id INT NULL REFERENCES Users(Id),
  Status NVARCHAR(50) NOT NULL DEFAULT 'active',
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  LastMessageAt DATETIME2 NULL
);

CREATE TABLE ChatMessages (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  SessionId INT NOT NULL REFERENCES ChatSessions(Id) ON DELETE CASCADE,
  SessionType NVARCHAR(20) NOT NULL,
  SenderId INT NOT NULL REFERENCES Users(Id),
  ReceiverId INT NULL REFERENCES Users(Id),
  Message NVARCHAR(MAX) NOT NULL,
  Timestamp DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  ReadBy NVARCHAR(MAX) NULL,
  MessageType NVARCHAR(50) NOT NULL DEFAULT 'text'
);

CREATE TABLE Documents (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  TraineeId INT NOT NULL REFERENCES Trainees(Id) ON DELETE CASCADE,
  FileName NVARCHAR(255) NOT NULL,
  DocumentType NVARCHAR(100) NOT NULL DEFAULT 'other',
  UploadDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  FileSize NVARCHAR(50) NULL,
  FileType NVARCHAR(200) NULL,
  Description NVARCHAR(MAX) NULL,
  UploadedBy INT NOT NULL REFERENCES Users(Id),
  Status NVARCHAR(50) NOT NULL DEFAULT 'active',
  Version NVARCHAR(50) NOT NULL DEFAULT '1.0',
  LastModified DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE HelpRequests (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  TaskId INT NULL REFERENCES Tasks(Id) ON DELETE SET NULL,
  TraineeId INT NOT NULL REFERENCES Trainees(Id) ON DELETE CASCADE,
  Message NVARCHAR(MAX) NOT NULL,
  Status NVARCHAR(50) NOT NULL DEFAULT 'pending',
  Urgency NVARCHAR(50) NOT NULL DEFAULT 'medium',
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  ResolvedAt DATETIME2 NULL,
  ResolvedBy INT NULL REFERENCES Users(Id),
  ResponseMessage NVARCHAR(MAX) NULL,
  ChatSessionId INT NULL REFERENCES ChatSessions(Id)
);

CREATE TABLE TraineePlans (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  TraineeId INT NOT NULL UNIQUE REFERENCES Trainees(Id) ON DELETE CASCADE,
  Title NVARCHAR(255) NOT NULL,
  Description NVARCHAR(MAX) NULL,
  StartDate DATE NOT NULL,
  EndDate DATE NOT NULL,
  Status NVARCHAR(50) NOT NULL DEFAULT 'active',
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE PlanMilestones (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  PlanId INT NOT NULL REFERENCES TraineePlans(Id) ON DELETE CASCADE,
  Title NVARCHAR(255) NOT NULL,
  Description NVARCHAR(MAX) NULL,
  DueDate DATE NULL,
  Status NVARCHAR(50) NOT NULL DEFAULT 'pending',
  DisplayOrder INT NOT NULL DEFAULT 1,
  CompletedDate DATETIME2 NULL,
  Notes NVARCHAR(MAX) NULL,
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE PlanGoals (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  PlanId INT NOT NULL REFERENCES TraineePlans(Id) ON DELETE CASCADE,
  Title NVARCHAR(255) NOT NULL,
  Description NVARCHAR(MAX) NULL,
  TargetDate DATE NULL,
  Status NVARCHAR(50) NOT NULL DEFAULT 'on-track',
  Progress INT NOT NULL DEFAULT 0
);
